### ISSUE TITLE
Avaibility of AP-Ref2Seq & ACMLM

### ISSUE THREAD

**Issue by diegoantognini** [nijianmo/recsys_justification#1]
Dear authors,

Thank you very much for your work and for sharing the code. I was wondering when would you release the code for the models AP-Ref2Seq & ACMLM.

Thank you in advance for your answer.

**Comment by nijianmo** [comment]
Hi, thanks for reaching out! I am busy preparing some deadlines and would release the code later (hopefully late December).

Thanks.

**Comment by diegoantognini** [comment]
Thank you for your answer. Looking forward playing with it !
