### ISSUE TITLE
acmlm

### ISSUE THREAD

**Issue by lileipisces** [nijianmo/recsys_justification#2]
Thanks for the code. I am quite interested in your work, but I cannot find the code of acmlm. If possible, could you tell me which file corresponds to the model acmlm?

**Comment by nijianmo** [comment]
We don't have time to clean code for that part yet due to plenty of deadlines recently. We hope to release it in late December or early January. Thanks!

**Comment by lthoang** [comment]
Hi @nijianmo,
Could you please make the source code of ACMLM available soon?

**Comment by nijianmo** [comment]
Hi, I have uploaded the code for ACMLM. To use it, you should prepare the old huggingface repo for BERT: "pytorch-pretrained-bert". Hope this helps.

**Comment by lileipisces** [comment]
Got it. Thanks.
