### ISSUE TITLE
Links for config and pre-trained weights of BERT Classifier unavailablee

### ISSUE THREAD

**Issue by diegoantognini** [nijianmo/recsys_justification#3]
Hi,

Sadly, both links lead to Error 404
http://deepyeti.ucsd.edu/jianmo/recsys_justification/model/justification_classifier/bert_config.json
http://deepyeti.ucsd.edu/jianmo/recsys_justification/model/justification_classifier/pytorch_model.bin

Could you please update these ?

Thanks !

**Comment by nijianmo** [comment]
Oh, it should work now.

**Comment by diegoantognini** [comment]
Thanks !
