### ISSUE TITLE
Data preparation ACMLM

### ISSUE THREAD

**Issue by XogoX** [nijianmo/recsys_justification#4]
Dear authors,

Thank you for sharing the code. I'm interesting by your ACMLM model but unfortunately, the data preprocessing part is not available and not the same as Ref2Seq.

Could you please update the corresponding code or explain how to compute the following fields:
```
        self.user_fa = env['user_fa'] 
        self.item_fa = env['item_fa'] 
        self.fa2tokids = env['fa2tokids']
        self.fa2idx = env['fa2idx']
        self.idx2fa = env['idx2fa']
```

**Comment by nijianmo** [comment]
Hi, the 'user_fa' and 'item_fa' are the fine aspect profile for user and item. The 'fa2tokids' is related to the position of fine aspect in the review. I've uploaded a few scripts to prepare the data. Hope this helps.

**Comment by XogoX** [comment]
@nijianmo Thank you very much!
