### ISSUE TITLE
dataset not found

### ISSUE THREAD

**Issue by tzin2018** [nijianmo/recsys_justification#5]
When training the ref2seq model,I can not find the file named env.json. Would you tell me how to get this file to run the model?

**Comment by nijianmo** [comment]
Hi, it's a file generated when preprocessing the dataset. You can obtain that file by run `prep_yelp.py`.

**Comment by tzin2018** [comment]
Thanks for your reply!




田智
1071229901@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nijianmo/recsys_justification"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月19日(星期六) 凌晨3:09
收件人:&nbsp;"nijianmo/recsys_justification"<recsys_justification@noreply.github.com&gt;;
抄送:&nbsp;"1071229901"<1071229901@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nijianmo/recsys_justification] dataset not found (#5)





 
Hi, it's a file generated when preprocessing the dataset. You can obtain that file by run prep_yelp.py.
